variable "cpus" {
  type    = number
  default = 1
}

variable "cpu_cores" {
  type = number
  default = 1
}

variable "disk_size" {
  type    = number
  default = 10000
}

variable "insecure_connection" {
  type    = bool
  default = false
}

variable "iso_checksum" {
  type    = string
  default = "sha256:d1f2bf834bbe9bb43faf16f9be992a6f3935e65be0edece1dee2aa6eb1767423"
}

variable "iso_url" {
  type    = string
  default = "http://releases.ubuntu.com/20.04/ubuntu-20.04.2-live-server-amd64.iso"
}

variable "iso_paths" {
  type    = list(string)
  default = [""]
}

variable "memory" {
  type    = number
  default = 1024
}

variable "name" {
  type    = string
  default = "ubuntu-20.04"
}

variable "vcenter_cluster" {
  type    = string
  default = ""
}

variable "vcenter_datastore" {
  type    = string
  default = ""
}

variable "vcenter_folder" {
  type    = string
  default = ""
}

variable "vcenter_network" {
  type    = string
  default = ""
}

variable "vcenter_password" {
  type    = string
  default = ""
}

variable "vcenter_server" {
  type    = string
  default = ""
}

variable "convert_template" {
  type    = bool
  default = false
}

variable "vcenter_username" {
  type    = string
  default = ""
}

variable "http_directory" {
  type = string
  default = ""
}

source "vsphere-iso" "autogenerated_1" {
  boot_command        = [
    "<esc><enter><f6><esc>",
    "autoinstall ds=nocloud-net;s=http://{{ .HTTPIP }}:{{ .HTTPPort }}/",
    "<enter><wait30m>"
  ]
  boot_wait           = "5s"
  cluster             = "${var.vcenter_cluster}"
  convert_to_template = "${var.convert_template}"
  CPUs                = "${var.cpus}"
  cpu_cores = "${var.cpu_cores}"
  datastore           = "${var.vcenter_datastore}"
  folder              = "${var.vcenter_folder}"
  guest_os_type       = "ubuntu64Guest"
  http_directory      = "${var.http_directory}"
  cdrom_type = "sata"
  insecure_connection = "${var.insecure_connection}"
  iso_checksum        = "${var.iso_checksum}"
  #iso_url             = "${var.iso_url}"
  iso_paths = "${var.iso_paths}"
  network_adapters {
    network      = "${var.vcenter_network}"
    network_card = "vmxnet3"
  }
  password         = "${var.vcenter_password}"
  RAM              = "${var.memory}"
  shutdown_command = "echo 'vagrant' | sudo -S shutdown -P now"
  ssh_password     = "ubuntu"
  ssh_timeout      = "30m"
  ssh_username     = "ubuntu"
  disk_controller_type = ["lsilogic-sas"]
  storage {
    disk_size = "${var.disk_size}"
    disk_thin_provisioned = true
  }
  username       = "${var.vcenter_username}"
  vcenter_server = "${var.vcenter_server}"
  vm_name        = "${var.name}-${formatdate("MMM DD, YYYY","${timestamp()}")}"
}

build {
  sources = ["source.vsphere-iso.autogenerated_1"]
}
